pool: devops-agent

trigger:
 branches:
   include:
     - main
     - feature/*

pr:
  branches:
    include:
      - main

parameters:
  - name: environment
    displayName: "Target Environment"
    type: string
    default: dev
    values:
      - dev
      - prod

  - name: runTerraformFmt
    displayName: "Run Terraform Format Check"
    type: boolean
    default: true

  - name: runTerraformValidate
    displayName: "Run Terraform Validate"
    type: boolean
    default: true

  - name: runTflintScanning
    displayName: "Run TFlint Scanning"
    type: boolean
    default: true

  - name: runTrivyScanning
    displayName: "Run Trivy Scanning"
    type: boolean
    default: true

  - name: runCheckov
    displayName: "Run Checkov Scanning"
    type: boolean
    default: true

  - name: runTerracost
    displayName: "Run Terracost"
    type: boolean
    default: true


variables:
  terraformVersion: "1.16.5"

  workingDirectory: '$(System.DefaultWorkingDirectory)/'


stages:
  - stage: validate
    displayName: "Validation Stage"
    jobs:
      - job: validate
        displayName: "Validation Stage"
        steps:
        - task: TerraformInstaller@1
          displayName: "Install Terraform"
          inputs:
            terraformVersion: "$(terraformVersion)"
      
        - ${{ if eq(parameters.runTerraformFmt, true) }}:
          - task: PowerShell@2
            displayName: "Terraform Format Check"
            inputs:
              targetType: 'inline'
              script: 'terraform fmt -check -recursive'

        - task: TerraformTask@5
          displayName: "Terraform Init"
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workingDirectory)'
            backendServiceArm: 'devops-svc'
            backendAzureRmResourceGroupName: 'terraform-state-rg'
            backendAzureRmStorageAccountName: 'heartfeltstate1234'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'heartfelt.tfstate'

        - ${{ if eq(parameters.runTerraformValidate, true) }}:
          - task: TerraformTask@5
            displayName: "Terraform Validate"
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(workingDirectory)'
              backendServiceArm: 'devops-svc'
              backendAzureRmResourceGroupName: 'terraform-state-rg'
              backendAzureRmStorageAccountName: 'heartfeltstate1234'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'heartfelt.tfstate'
          
  - stage: scanning
    displayName: "Scanning Stage"
    jobs:
      - job: tflintscanning
        displayName: "TFLINT"
        steps:

        - ${{ if eq(parameters.runTflintScanning, true) }}:
          - task: PowerShell@2
            displayName: "TFLINT"
            inputs:
              targetType: 'inline'
              script: |
                tflint --init
                tflint --recursive --format json > tflint-report.json

      - job: trivyscanning
        displayName: "Trivy Terraform Security Scan"
        steps:
        
        - ${{ if eq(parameters.runTrivyScanning, true) }}:
        
          - task: PowerShell@2
            displayName: "Trivy Terraform Security Scan"
            inputs:
              targetType: 'inline'
              script: trivy config --severity HIGH,CRITICAL --exit-code 1 "$(workingDirectory)"

      - job: checkovscanning
        displayName: "Checkov Security Scan"
        steps:
          
        - ${{ if eq(parameters.runCheckov, true) }}:

          - task: PowerShell@2
            displayName: "Checkov Security Scan"
            inputs:
              targetType: 'inline'
              script: checkov -d "$(workingDirectory)"

      - job: terracost
        displayName: "Terracost Estimation"
        steps:
        

        - ${{ if eq(parameters.runTerracost, true) }}:

          - task: PowerShell@2
            displayName: "Terracost Estimation"
            inputs:
              targetType: 'inline'
              script: terracost breakdown --path "$(workingDirectory)"

  - stage: DevPlan
    displayName: "Development - Terraform Plan"
    dependsOn: validate
    condition: and(succeeded(), eq('${{ parameters.environment }}', 'dev'))
    jobs:
      - job: TerraformPlan
        displayName: "Terraform Plan - Dev"
        steps:

        - task: TerraformInstaller@1
          displayName: "Install Terraform"
          inputs:
            terraformVersion: "$(terraformVersion)"

        - task: TerraformTask@5
          displayName: "Terraform Init"
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workingDirectory)'
            backendServiceArm: 'devops-svc'
            backendAzureRmResourceGroupName: 'terraform-state-rg'
            backendAzureRmStorageAccountName: 'heartfeltstate1234'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'heartfelt.tfstate'

        - task: TerraformTask@5
          displayName: "Terraform Plan - Dev"
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/'
            environmentServiceNameAzureRM: 'devops-svc'

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/dev.tfplan'
            artifact: 'terraform-dev-plan'
            # publishLocation: 'pipeline'