pool: devops-agent

trigger:
 branches:
   include:
     - main
     - feature/*

pr:
  branches:
    include:
      - main

parameters:
  - name: environment
    displayName: "Target Environment"
    type: string
    default: dev
    values:
      - dev
      - prod

  - name: runTerraformFmt
    displayName: "Run Terraform Format Check"
    type: boolean
    default: true

  - name: runTerraformValidate
    displayName: "Run Terraform Validate"
    type: boolean
    default: true

variables:
  terraformVersion: "1.13.5"

  workingDirectory: '$(System.DefaultWorkingDirectory)/'


stages:
  - stage: validate
    displayName: "Validation Stage"
    jobs:
      - job: validate
        displayName: "Validation Stage"
        steps:
        - task: TerraformInstaller@1
          displayName: "Install Terraform"
          inputs:
            terraformVersion: "$(terraformVersion)"
      
        - ${{ if eq(parameters.runTerraformFmt, true) }}:
          - task: PowerShell@2
            displayName: "Terraform Format Check"
            inputs:
              targetType: 'inline'
              script: 'terraform fmt -check -recursive'

        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workingDirectory)'
            backendServiceArm: 'ss'
            backendAzureRmResourceGroupName: 'terraform-state-rg'
            backendAzureRmStorageAccountName: 'heartfeltstate1234'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'heartfelt.tfstate'

        - ${{ if eq(parameters.runTerraformValidate, true) }}:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(workingDirectory)'
          
